# test classe distanzaCitta

##
##import colorama
##from colorama import Fore
##from colorama import Style
##
##colorama.init()
##print(Fore.BLUE + Style.BRIGHT + "This is the color of the sky" + Style.RESET_ALL)
##print(Fore.GREEN + "This is the color of grass" + Style.RESET_ALL)
##print(Fore.BLUE + Style.DIM + "This is a dimmer version of the sky" + Style.RESET_ALL)
##print(Fore.YELLOW + "This is the color of the sun" + Style.RESET_ALL)
##



# esempio uso
print('start importazione')
import distanzacitta


d = distanzacitta.distanzaTraCitta(verbose=False, shortDF = False)
result, dist, tempo= d.distanzaNomeA2NomeB('Capriate San Gervasio', 'Capriate San Gervasio')
result, dist, tempo= d.distanzaNomeA2NomeB('parabiago', 'milano')
print("distanza [m]:" + str(dist) +" tempo di percorrenza [minuti]: " +str(tempo))

lista_destinazioni       = ["ABBIATEGRASSO","AGRATE BRIANZA","ALBAIRATE","ALBESE CON CASSANO","ALBIZZATE","ALESSANDRIA","ANTEGNATE","APPIANO GENTILE","ARCISATE","ARCONATE","ARCORE","ARESE","ARLUNO","AROSIO","ARSAGO SEPRIO","ASSAGO","BAGNATICA","BARANZATE","BARBARIGA","BAREGGIO","BARLASSINA","BASIGLIO","BERGAMO 1","BERGAMO 2","BERGAMO 3","BERGAMO 4","BERGAMO 5","BERGAMO 6","BERGAMO 7","BERNAREGGIO","BERNATE TICINO","BESATE","BESNATE","BESOZZO","BIELLA","BINASCO","BODIO LOMNAGO","BOFFALORA SOPRA TICINO","BOLLATE","BOVISIO MASCIAGO","BREGNANO","BRESCIA 1","BRESCIA 2","BRESCIA 3","BRESCIA 4","BRESCIA 5","BRESCIA 6","BRESCIA 7","BRESCIA 8","BRESCIA 9","BRESSO","BRIOSCO","BRIVIO","BRUGHERIO","BRUNELLO","BUCCINASCO","BUGUGGIATE","BURAGO DI MOLGORA","BUSCATE","BUSTO ARSIZIO 1","BUSTO ARSIZIO 2","BUSTO GAROLFO","CADORAGO","CADREZZATE - OSMATE","CAIRATE","CAMBIAGO","CANEGRATE","CANTU'","CAPIAGO INTIMIANO","CAPONAGO","CARBONATE","CARDANO AL CAMPO","CARIMATE","CARNAGO","CARONNO PERTUSELLA","CARONNO VARESINO","CARPIANO","CARUGATE","CARUGO","CASALMAGGIORE","CASALPUSTERLENGO","CASATENOVO","CASCIAGO","CASNATE CON BERNATE","CASORATE PRIMO","CASORATE SEMPIONE","CASOREZZO","CASSANO MAGNAGO","CASSINA DE PECCHI","CASSINETTA DI LUGAGNANO","CASSOLNOVO","CASTANO PRIMO","CASTELLANZA","CASTELLO CABIAGLIO","CASTELNUOVO BOZZENTE","CASTIGLIONE DELLE STIVIERE","CASTIGLIONE OLONA","CASTREZZATO","CASTRONNO","CAVARIA CON PREMEZZO","CAVENAGO DI BRIANZA","CAZZAGO BRABBIA","CERIANO LAGHETTO","CERMENATE","CERNUSCO SUL NAVIGLIO","CERRO MAGGIORE","CESANO BOSCONE","CESANO MADERNO","CESATE","CINISELLO BALSAMO 1","CINISELLO BALSAMO 2","CIRIMIDO","CISLAGO","CISLIANO","CODOGNO","COGLIATE","COLOGNO MONZESE","COMERIO","COMO 1","COMO 2","COMO 3","COMO 4","COMO 5","COMO 6","COMO 7","COMO 8","COMO 9","CONCOREZZO","CORBETTA","CORMANO","CORNAREDO","CORSICO","CORTEOLONA","CREDARO","CUGGIONO","CUNARDO - MASCIAGO PRIMO","CUSAGO","CUSANO MILANINO","DAIRAGO","DALMINE","DESIO","FAGNANO OLONA","FALOPPIO","FENEGRO'","FERNO","FERRERA ERBOGNONE","FINO MORNASCO","GAGGIANO","GALLARATE","GANDINO","GARBAGNATE MILANESE","GAVIRATE","GAZZADA - SCHIANNO","GERENZANO","GERMIGNAGA","GIUSSAGO - ROGNANO","GIUSSANO","GORGONZOLA","GORLA MAGGIORE","GORLA MINORE","GORLE","GORNATE OLONA","GRANDATE","GRAVELLONA LOMELLINA","GUANZATE","INDUNO OLONA","INVERUNO","INZAGO","JERAGO CON ORAGO","LACCHIARELLA","LAINATE","LANDRIANO","LAZZATE","LECCO","LEGNANO 1","LEGNANO 2","LENTATE SUL SEVESO","LIGURIA","LIMBIATE","LIMIDO COMASCO","LISCATE","LISSONE","LOCATE DI TRIULZI","LOCATE VARESINO","LODI 1","LODI 2","LOMAZZO","LONATE CEPPINO","LONATE POZZOLO","LURAGO MARINONE","LURATE CACCIVIO","MAGENTA","MAGNAGO","MALNATE","MARCALLO CON CASONE","MARCHE","MARIANO COMENSE","MARNATE","MEDA","MEDIGLIA","MEDOLAGO","MELEGNANO","MELZO","MERATE","MESERO","MEZZAGO","MILANO 1","MILANO 10","MILANO 11","MILANO 12","MILANO 13","MILANO 14","MILANO 15","MILANO 16","MILANO 2","MILANO 3","MILANO 4","MILANO 5","MILANO 6","MILANO 7","MILANO 8","MILANO 9","MISINTO","MOLTENO","MONZA 1","MONZA 2","MONZA 3","MONZA 4","MONZA 5","MORAZZONE","MORIMONDO","MORNAGO","MORTARA","MOTTA VISCONTI","MOZZATE","MUGGIO'","NERVIANO","NIBIONNO","NOSATE","NOVA MILANESE","NOVARA","NOVATE MILANESE","NOVIGLIO","OGGIONA CON SANTO STEFANO","OLGIATE COMASCO","OLGIATE OLONA","OPERA","ORIGGIO","OSNAGO","OSSONA","PADERNO DUGNANO","PARABIAGO","PARATICO","PARONA","PAVIA 1","PAVIA 2","PERO","PESCHIERA BORROMEO","PIAN CAMUNO","PIEVE EMANUELE","PIOLTELLO","POGLIANO MILANESE","PORTO VALTRAVAGLIA","POZZO D'ADDA","POZZUOLO MARTESANA","PREGNANA MILANESE","RESCALDINA","RHO 1","RHO 2","RHO 3","RIVANAZZANO TERME - ROCCA SUSELLA","ROBECCHETTO CON INDUNO","ROBECCO SUL NAVIGLIO","RODANO","ROE' VOLCIANO","ROGENO","ROMANENGO","ROMANO DI LOMBARDIA","ROSATE","ROVELLASCA","ROVELLO PORRO","ROZZANO","SAMARATE","SAN DONATO MILANESE","SAN FERMO DELLA BATTAGLIA","SAN GIORGIO SU LEGNANO","SAN GIULIANO MILANESE","SAN VITTORE OLONA","SANTO STEFANO TICINO","SARONNO","SEDRIANO","SEGRATE","SENAGO","SEREGNO","SESTO CALENDE","SESTO SAN GIOVANNI 1","SESTO SAN GIOVANNI 2","SETTALA","SETTIMO MILANESE","SEVESO","SIZIANO","SOLARO","SOLBIATE ARNO","SOLBIATE OLONA","SOMMA LOMBARDO","SUMIRAGO","TAVAZZANO CON VILLAVESCO","TERNATE","TORINO","TORRE BOLDONE","TRADATE","TRAVACO' SICCOMARIO","TREMOSINE","TRENZANO","TREVIGLIO","TREZZANO ROSA","TREZZANO SUL NAVIGLIO","TRIBIANO","TRIUGGIO","TURATE","TURBIGO","UBOLDO","UGGIATE - TREVANO","USMATE VELATE","VALBREMBO","VALERA FRATTA","VANZAGHELLO","VANZAGO","VARANO BORGHI","VAREDO","VARESE 1","VARESE 2","VARESE 3","VARESE 4","VARESE 5","VEDANO AL LAMBRO","VEDANO OLONA","VEDUGGIO CON COLZANO","VENEGONO INFERIORE","VENEGONO SUPERIORE","VENIANO","VERBANO - OSSOLA","VERGIATE","VERMEZZO","VIGEVANO 1","VIGEVANO 2","VIGGIU'","VIGNATE","VILLA CORTESE","VILLA GUARDIA","VILLASANTA","VIMERCATE","VIMODRONE","VITTUONE","VIZZOLA TICINO","VOGHERA","ZECCONE","ZELO SURRIGONE","ZERBOLO'","ZIBIDO SAN GIACOMO"]

for paese in lista_destinazioni:
    origine = 'parabiago'
    result, dist, tempo= d.distanzaNomeA2NomeB(origine, paese)
    if result == -1:
        #print (Fore.RED + paese + Style.RESET_ALL)
        print (paese)
    else:
        print(origine + "-" + paese + ": distanza [m]:" + str(dist) +" tempo di percorrenza [minuti]: " +str(tempo))
    
